version: '3.9'

services:
    bot:
        build: .
        restart: always
        entrypoint: scripts/run.sh
        volumes:
            - ".:/bot"
            - "/tmp/bridge-bot:/tmp"
        depends_on:
            - mongodb
        logging:
            driver: json-file
            options:
                max-size: "5m"
                max-file: "20"


    mongodb:
        image: mongo
        restart: always
        command: mongod --port ${MONGODB_PORT}
        volumes:
            - "/var/lib/mongodb-bridge-bot:/data/db"
